### ISSUE TITLE
Visual Studio for Mac 2017

### ISSUE THREAD

**Issue by martinlodewyks** [kiebor/PlantUml-Language-Service#2]
Hi,

Do you have any intention to port this to Mac as well?  Would like to try it out as we are moving all our diagramming and design PlantUML.

Cheers,
Martin

**Comment by kiebor** [comment]
Hi Martin,

I'm not sure if it could be ported easily as it uses the. Net system io name's pace for the '!include' option, essentially reading the content on the included file and inserting at the start of the file (bit of a hack, I know, but the simplest way I could think to respect the preprocessor keyword). It may be possible if converted to. Net core I suppose.

I originally created this for my own use after Ms removed the architecture tools from Visual Studio. Plantuml was a simple and easy to use substitute. I'm guessing you're thoughts are similar. I will have a think on what is needed, and look at the effort involved; if you would like to fork, we can investigate a mac port or individual version together if you like.

Thanks for your interest.
