### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by newbrain** [kiebor/PlantUml-Language-Service#7]
Please update for the newly released VS 2019.

I actually managed to install it in VS 2019 Community by manually tweaking some of the manifest files; sorry for not proposing a PR, but it was a bit of blind hacking.

**Comment by nmocruz** [comment]
can you share it somehow ?

**Comment by kiebor** [comment]
Solution has been updated for VS2019 and a new package has been published to VS market place.

**Comment by newbrain** [comment]
Great! Thanks a lot.
