### ISSUE TITLE
Visual Studio MPF 15.0 missing

### ISSUE THREAD

**Issue by wilhelmmedetz** [kiebor/PlantUml-Language-Service#8]
When trying to install the PlantUml extension in Visual Studio 2019 I get the following error message:

Dependency Alert
The following references must be present before installation can continue:
Visual Studio MPF 15.0

I have Visual Studio 2017 not installed.

**Comment by kiebor** [comment]
@wilhelmmedetz 
Thanks, I've identified the problem with this line from the manifest:

https://github.com/kiebor/PlantUml-Language-Service/blob/374b82e8ab6ad3e815c6fefc96311c9a545f5db4/src/source.extension.vsixmanifest#L20

According to Mads Kristensen, it is safe to remove.

I'm not anywhere near a VS instance right now -- but will make the necessary changes asap.

Thanks for spotting this.

**Comment by kiebor** [comment]
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/
